# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4248168f274518468fddb13d27bdd55674cd4e4eba7a4d9f9573c76c2d996e051a2797e2bcd1f3560fb5bfe3fedfd4c8efe23bb72d485f85c8d9ad1eab229f43

test:
  secret_key_base: 331827cf7f06f12741b8a4870234b4addeb86677562d5790f83022113f4a9c0a438e77c2bfaf254185f2bd20f36ccc0434b7713fa301c60e41cecab3baf942ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
